title:            Main Page of LIU LIN 
tagline:          main page
description:      Describe your main page.
# server
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Owner/author information
owner:
  name:           Liu Lin
  email:          liulin8796@126.com
  github:         https://github.com/mumufeixia
  stackoverflow: http://stackoverflow.com/users/****
  tsina:          http://weibo.com/u/****
  weixin:         http://***.jpg
  disqus:         **** 
social:
    - icon: fa-weixin
      link: "http://mumufeixia.github.io/public/images/wechat.jpg"
    - icon: fa-weibo
      link: "http://weibo.com/u/2830658314"
    - icon: fa-twitter
      link: "https://twitter.com/akulubala"
    - icon: fa-github
      link: "https://github.com/akulubala"
    - icon: fa-stack-overflow
      link: "http://stackoverflow.com/users/1364309"
root: /  
layout : null
# Links to include in top navigation
# For external links add external: true
links:
  - title: PHP
    url : posts/php.html
  - title: Javascript
    url : posts/javascript.html
  - title: JQuery
    url : posts/jquery.html 
  - title: Mysql
    url : posts/mysql.html
  - title: Mongodb
    url : posts/mongodb.html
  - title: Zend Framework 2
    url : posts/zf2.html
  - title: laravel
    url : posts/laravel.html
  - title: Git
    url : posts/git.html
  - title: Linux
    url : posts/linux.html
  - title : Redis
    url : posts/redis.html
  - title : Python
    url : posts/python.html

exclude_from_search: true

lunr_search:
         excludes: [rss.xml, atom.xml, index.html, python.html, git.html, javascript.html, laravel.html, linux.html, mongodb.html, mysql.html, php.html, redis.html, rails.html, ruby.html, zf2.html, about.html]
         stopwords: "stopwords.txt"
         min_length: 3
         
markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  
permalink:   /:categories/:year/:month/:day/:title.html
# 
# include: [".htaccess"]
exclude: ["log", "Rakefile", "Rakefile.rb", "Gemfile","Gemfile.lock","README.md"]
# pagination
paginate: 10
paginate_path: "page:num"
